/* Generated By:JJTree: Do not edit this line. ASTAndExp.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package AST;

public class ASTAndExp extends SimpleNode {
  public ASTAndExp(int id) {
    super(id);
  }

  public ASTAndExp(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=946cfac0664b37e60496216d25207e51 (do not edit this line) */
