package AST;

/* Generated By:JJTree: Do not edit this line. AST.ASTBoolExp.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTBoolExp extends SimpleNode {

  public enum EXP_TYPE { EQ, NEQ, LT, LEQ, GT, GEQ }

  public EXP_TYPE type;

  public ASTBoolExp(int id) {
    super(id);
  }

  public ASTBoolExp(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=89d7a86d95a2ebc9def011917df02713 (do not edit this line) */
