/* Generated By:JJTree: Do not edit this line. ASTExpoExp.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package AST;

public class ASTExpoExp extends SimpleNode {
  public ASTExpoExp(int id) {
    super(id);
  }

  public ASTExpoExp(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=125c4de6a92e26f8fe6fb5203aeef925 (do not edit this line) */
