/* Generated By:JJTree: Do not edit this line. ASTFuncParams.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package AST;

public class ASTFuncParams extends SimpleNode {
  public ASTFuncParams(int id) {
    super(id);
  }

  public ASTFuncParams(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8168b627bfaef673d74ce6c4da89ff2f (do not edit this line) */
