/* Generated By:JJTree: Do not edit this line. ASTFunctionCall.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package AST;

public class ASTFunctionCall extends SimpleNode {
  public ASTFunctionCall(int id) {
    super(id);
  }

  public ASTFunctionCall(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bac5256cbf86b8121b32e6d1edb2af43 (do not edit this line) */
