/* Generated By:JJTree: Do not edit this line. ASTFuncParam.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package AST;

public class ASTFuncParam extends SimpleNode {
  public ASTFuncParam(int id) {
    super(id);
  }

  public ASTFuncParam(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d26445bc12c5bd2cb7579c64544e1c5c (do not edit this line) */
