/* Generated By:JJTree: Do not edit this line. ASTIfStmt.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package AST;

public class ASTIfStmt extends SimpleNode {
  public ASTIfStmt(int id) {
    super(id);
  }

  public ASTIfStmt(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f7803440bf5ec103206b3a299171ca40 (do not edit this line) */
