/* Generated By:JJTree: Do not edit this line. ASTNumberLiteral.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package AST;

public class ASTNumberLiteral extends SimpleNode {
  public ASTNumberLiteral(int id) {
    super(id);
  }

  public ASTNumberLiteral(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cf11aea9c29065e39ed48f24d202137b (do not edit this line) */
