package AST;

/* Generated By:JJTree: Do not edit this line. AST.ASTPrefixExp.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTPrefixExp extends SimpleNode {

  public enum OP {INC, DEC, NOT}
  public OP op;

  public ASTPrefixExp(int id) {
    super(id);
  }

  public ASTPrefixExp(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4c915b8e9b3b46980084431d203065ee (do not edit this line) */
