/* Generated By:JJTree: Do not edit this line. ASTParams.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package AST;

public class ASTParams extends SimpleNode {
  public ASTParams(int id) {
    super(id);
  }

  public ASTParams(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9aee40815570c730d640840fe491c10d (do not edit this line) */
