/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 4.1d1 */
package AST;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTFUNCTION = 1;
  public int JJTVOID = 2;
  public int JJTIDENTIFIER = 3;
  public int JJTFUNCPARAMS = 4;
  public int JJTFUNCPARAM = 5;
  public int JJTBLOCK = 6;
  public int JJTVARDECL = 7;
  public int JJTTYPE = 8;
  public int JJTASSIGNMENTEXP = 9;
  public int JJTOREXP = 10;
  public int JJTANDEXP = 11;
  public int JJTBOOLEXP = 12;
  public int JJTADDEXP = 13;
  public int JJTMULEXP = 14;
  public int JJTEXPOEXP = 15;
  public int JJTPREFIXEXP = 16;
  public int JJTSUFFIXEXP = 17;
  public int JJTACCESSEXP = 18;
  public int JJTSUBSCRIPT = 19;
  public int JJTFUNCTIONCALL = 20;
  public int JJTNUMBERLITERAL = 21;


  public String[] jjtNodeName = {
    "Start",
    "Function",
    "void",
    "Identifier",
    "FuncParams",
    "FuncParam",
    "Block",
    "VarDecl",
    "Type",
    "AssignmentExp",
    "OrExp",
    "AndExp",
    "BoolExp",
    "AddExp",
    "MulExp",
    "ExpoExp",
    "PrefixExp",
    "SuffixExp",
    "AccessExp",
    "Subscript",
    "FunctionCall",
    "NumberLiteral",
  };
}
/* JavaCC - OriginalChecksum=545647a0d3736fab1f9cefd3bfa612dc (do not edit this line) */
