/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 4.1d1 */
package AST;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTFUNCTION = 1;
  public int JJTVOID = 2;
  public int JJTIDENTIFIER = 3;
  public int JJTFUNCPARAMS = 4;
  public int JJTFUNCPARAM = 5;
  public int JJTBLOCK = 6;
  public int JJTBREAKSTMT = 7;
  public int JJTRETURNSTMT = 8;
  public int JJTVARDECL = 9;
  public int JJTIFSTMT = 10;
  public int JJTCONDITION = 11;
  public int JJTWHILESTMT = 12;
  public int JJTTYPE = 13;
  public int JJTASSIGNMENTEXP = 14;
  public int JJTOREXP = 15;
  public int JJTANDEXP = 16;
  public int JJTBOOLEXP = 17;
  public int JJTADDEXP = 18;
  public int JJTMULEXP = 19;
  public int JJTEXPOEXP = 20;
  public int JJTPREFIXEXP = 21;
  public int JJTSUFFIXEXP = 22;
  public int JJTACCESSEXP = 23;
  public int JJTSUBSCRIPT = 24;
  public int JJTFUNCTIONCALL = 25;
  public int JJTPARAMS = 26;
  public int JJTNUMBERLITERAL = 27;


  public String[] jjtNodeName = {
    "Start",
    "Function",
    "void",
    "Identifier",
    "FuncParams",
    "FuncParam",
    "Block",
    "BreakStmt",
    "ReturnStmt",
    "VarDecl",
    "IfStmt",
    "Condition",
    "WhileStmt",
    "Type",
    "AssignmentExp",
    "OrExp",
    "AndExp",
    "BoolExp",
    "AddExp",
    "MulExp",
    "ExpoExp",
    "PrefixExp",
    "SuffixExp",
    "AccessExp",
    "Subscript",
    "FunctionCall",
    "Params",
    "NumberLiteral",
  };
}
/* JavaCC - OriginalChecksum=a9d7a3f9c9c936a5b31f11076eb23273 (do not edit this line) */
