
public enum NodeOps {
    ROOT, FUNC, PARAMS, BLOCK,
    DECL, RETURN, IF, WHILE,
    ASSIGNX, ASSIGNPLUSX, ASSIGNMINUSX, ASSIGNTIMESX, ASSIGNDIVX, ASSIGNMODX,
    ORX, ANDX, EQX, NEQX, LTX, LEQX, GTX, GEQX,
    ADDX, SUBX, MULX, DIVX, MODX, EXPOX,
    PREINC, PREDEC, POSTINC, POSTDEC, NOT,
    SUBSCRIPT, CALL,
    VAR, TYPE
}
