package AST;/* Generated By:JJTree: Do not edit this line. AST.ASTAddExp.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */

import java.util.ArrayList;

public class ASTAddExp extends SimpleNode {

  public enum OP { PLUS, MINUS }
  public ArrayList<OP> op = new ArrayList<OP>();

  public ASTAddExp(int id) {
    super(id);
  }

  public ASTAddExp(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=be1c0c3a1e2b8b6c682eb0f23c2c5d30 (do not edit this line) */
