/* Generated By:JJTree: Do not edit this line. ASTAccessExp.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package AST;

public class ASTAccessExp extends SimpleNode {
  public ASTAccessExp(int id) {
    super(id);
  }

  public ASTAccessExp(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0bd424a687957fd4bbcce03e6043c0de (do not edit this line) */
