package AST;

/* Generated By:JJTree: Do not edit this line. AST.ASTAssignmentExp.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTAssignmentExp extends SimpleNode {

  public enum EXP_TYPE { ASSIGN, APLUS, AMINUS, AMUL, ADIV, AMOD }

  public EXP_TYPE type;

  public ASTAssignmentExp(int id) {
    super(id);
  }

  public ASTAssignmentExp(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b69707fdaa99de668a28c077df08ec3e (do not edit this line) */
