/* Generated By:JJTree: Do not edit this line. ASTBreakStmt.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package AST;

public class ASTBreakStmt extends SimpleNode {
  public ASTBreakStmt(int id) {
    super(id);
  }

  public ASTBreakStmt(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cf671aa69766982426c938403b3861b5 (do not edit this line) */
