/* Generated By:JJTree: Do not edit this line. ASTCondition.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package AST;

public class ASTCondition extends SimpleNode {
  public ASTCondition(int id) {
    super(id);
  }

  public ASTCondition(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c501141fd0f22416277c908fc8799b22 (do not edit this line) */
