/* Generated By:JJTree: Do not edit this line. ASTFunction.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package AST;

public class ASTFunction extends SimpleNode {
  public ASTFunction(int id) {
    super(id);
  }

  public ASTFunction(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e165f1bd1dc59ed7fc8b8e89aebba2d3 (do not edit this line) */
