/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package AST;

public class ASTIdentifier extends SimpleNode {

  public String image;

  public ASTIdentifier(int id) {
    super(id);
  }

  public ASTIdentifier(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=583bb3e1f59c8544f57f5a9c0b24f4e2 (do not edit this line) */
