/* Generated By:JJTree: Do not edit this line. ASTIntLiteral.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package AST;

public class ASTIntLiteral extends SimpleNode {

  public int val;
  public ASTIntLiteral(int id) {
    super(id);
  }

  public ASTIntLiteral(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9d1a6dd94569fbdf000bd857bfbdb865 (do not edit this line) */
