package AST;/* Generated By:JJTree: Do not edit this line. AST.ASTMulExp.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */

import java.util.ArrayList;

public class ASTMulExp extends SimpleNode {

  public enum OP { MUL, DIV, MOD }
  public ArrayList<OP> op = new ArrayList<OP>();

  public ASTMulExp(int id) {
    super(id);
  }

  public ASTMulExp(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7ef645b3c3d22c85b8537fce76d2e061 (do not edit this line) */
