/* Generated By:JJTree: Do not edit this line. ASTOrExp.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package AST;

public class ASTOrExp extends SimpleNode {
  public ASTOrExp(int id) {
    super(id);
  }

  public ASTOrExp(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5d6c79c5949b3901603da105721f9a5d (do not edit this line) */
