/* Generated By:JJTree: Do not edit this line. ASTReturnStmt.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package AST;

public class ASTReturnStmt extends SimpleNode {
  public ASTReturnStmt(int id) {
    super(id);
  }

  public ASTReturnStmt(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=647981aa6c458b9699b873378455a1ac (do not edit this line) */
