/* Generated By:JJTree: Do not edit this line. ASTRealLiteral.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package AST;

public class ASTRealLiteral extends SimpleNode {

  public double val;

  public ASTRealLiteral(int id) {
    super(id);
  }

  public ASTRealLiteral(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=99aacce751b585e2256c3c15f27feaa8 (do not edit this line) */
