/* Generated By:JJTree: Do not edit this line. ASTSubscript.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package AST;

public class ASTSubscript extends SimpleNode {
  public ASTSubscript(int id) {
    super(id);
  }

  public ASTSubscript(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=23040178e623a5b326063bd39169b488 (do not edit this line) */
