package AST;

/* Generated By:JJTree: Do not edit this line. AST.ASTSuffixExp.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
public class ASTSuffixExp extends SimpleNode {

  public enum OP {INC, DEC}
  public OP op;

  public ASTSuffixExp(int id) {
    super(id);
  }

  public ASTSuffixExp(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=177098873801f9d81ce94528fc6eb37b (do not edit this line) */
