/* Generated By:JJTree: Do not edit this line. ASTVarDecl.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package AST;

public class ASTVarDecl extends SimpleNode {
  public ASTVarDecl(int id) {
    super(id);
  }

  public ASTVarDecl(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2ba8c490f8bd8454991871e268fb930f (do not edit this line) */
