/* Generated By:JJTree: Do not edit this line. ASTWhileStmt.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package AST;

public class ASTWhileStmt extends SimpleNode {
  public ASTWhileStmt(int id) {
    super(id);
  }

  public ASTWhileStmt(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f6438daa868575ab46bbbf1394f0f03e (do not edit this line) */
