/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 4.1d1 */
package AST;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTFUNCTION = 1;
  public int JJTVOID = 2;
  public int JJTFUNCPARAMS = 3;
  public int JJTFUNCPARAM = 4;
  public int JJTBLOCK = 5;
  public int JJTBREAKSTMT = 6;
  public int JJTRETURNSTMT = 7;
  public int JJTVARDECL = 8;
  public int JJTIFSTMT = 9;
  public int JJTCONDITION = 10;
  public int JJTWHILESTMT = 11;
  public int JJTTYPE = 12;
  public int JJTASSIGNMENTEXP = 13;
  public int JJTOREXP = 14;
  public int JJTANDEXP = 15;
  public int JJTBOOLEXP = 16;
  public int JJTADDEXP = 17;
  public int JJTMULEXP = 18;
  public int JJTEXPOEXP = 19;
  public int JJTPREFIXEXP = 20;
  public int JJTSUFFIXEXP = 21;
  public int JJTACCESSEXP = 22;
  public int JJTSUBSCRIPT = 23;
  public int JJTFUNCTIONCALL = 24;
  public int JJTPARAMS = 25;
  public int JJTNUMBERLITERAL = 26;
  public int JJTIDENTIFIER = 27;


  public String[] jjtNodeName = {
    "Start",
    "Function",
    "void",
    "FuncParams",
    "FuncParam",
    "Block",
    "BreakStmt",
    "ReturnStmt",
    "VarDecl",
    "IfStmt",
    "Condition",
    "WhileStmt",
    "Type",
    "AssignmentExp",
    "OrExp",
    "AndExp",
    "BoolExp",
    "AddExp",
    "MulExp",
    "ExpoExp",
    "PrefixExp",
    "SuffixExp",
    "AccessExp",
    "Subscript",
    "FunctionCall",
    "Params",
    "NumberLiteral",
    "Identifier",
  };
}
/* JavaCC - OriginalChecksum=ab80fc578e42d690028c7029b3fc66fb (do not edit this line) */
